apiVersion: batch/v1
kind: Job
metadata:
  name: kind-test-sleep
spec:
  template:
    spec:
      containers:
      - name: sleep-container
        image: busybox:latest
        args:
        - /bin/sh
        - -c
        - "sleep 30"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
      restartPolicy: Never